// I got these from the article "List of Foods" on Wikipedia
const foodList = [
    "Asparagus",
    "Cookie",
    "Alfajor",
    "Lebkuchen",
    "Speculaas",
    "Cracker",
    "Hardtack",
    "Abernethy",
    "Bread",
    "bagel",
    "Bialy",
    "Croissant",
    "Baguette",
    "Toast",
    "Flatbread",
    "Arepa",
    "Pupusa",
    "Burrito",
    "Cabbage",
    "Cake",
    "Cupcake",
    "Chocolate",
    "Pancake",
    "Poundcake",
    "Cheese",
    "Brie",
    "Feta",
    "Parmesan",
    "Congee",
    "Donuts",
    "Jam",
    "Sprinkles",
    "Chocolate",
    "Dumplings",
    "Fun guo",
    "Har gow",
    "Pierogi",
    "Wonton",
    "Fruits",
    "Apricot",
    "Apple",
    "Banana",
    "Durian",
    "Cherry",
    "Kiwi",
    "Avocado",
    "Apricot",
    "Peach",
    "Pear",
    "Pineapple",
    "Blueberry",
    "Raspberry",
    "Cranberry",
    "Poutine",
    "Gravy",
    "Grains",
    "Cereal",
    "Corn",
    "Popcorn",
    "Rice",
    "Ice cream",
    "Chocolate",
    "Vanilla",
    "Queso",
    "Superman",
    "Spumoni",
    "Pistachio",
    "Moon mist",
    "Meats",
    "Beef",
    "Wagyu",
    "Steak",
    "Pork",
    "Bacon",
    "Ham",
    "Poultry",
    "Ribs",
    "Sausage",
    "Seafood",
    "Fish",
    "Salmon",
    "Eggs",
    "Omelette",
    "Tea egg",
    "Iron egg",
    "Soy egg",
    "Milk",
    "Soy milk",
    "Cow milk",
    "Goat milk",
    "Pasta",
    "Lasagna",
    "Linguini",
    "Ravioli",
    "Carbonara",
    "Bolognese",
    "Spaghetti",
    "Pudding",
    "Pie",
    "Apple pie",
    "Cream pie",
    "Peach pie",
    "Pizza",
    "Pepperoni",
    "Hawaiian",
    "Rolls",
    "Croquette",
    "Egg roll",
    "Lumpia",
    "Burrito",
    "Panini",
    "Whopper",
    "Hot dogs",
    "Soup",
    "Chowder",
    "Sinigang",
    "Sushi",
    "Stew",
    "Taco",
    "Tamale",
    "Taquitos",
    "Turnover",
    "Waffle",
    "Pancake"
];

export { foodList };
